### ISSUE TITLE
2.0.3 seems to have Missing manifest file which prevents uninstall

### ISSUE THREAD

**Issue by Damnatus** [akeeba/com_datacompliance#33]
Hi,

just tried the component and when I wanted to uninstall it via its package the error "Package Uninstall: Missing manifest file.
" appeared. 

I have deleted database entries and files manually - so no support request. Just want to let you know in case this is not expected or intended.

**Comment by nikosdion** [comment]
A Joomla extension **cannot be installed unless it has an XML manifest**. Remember that Joomla itself performs the installation and the manifest is how developers communicate to Joomla which files go where. 

For package extensions the manifest lists all sub–extensions to be installed and linked to the package. The package in and of itself does not install any files, code or database tables.

After Joomla performs the installation it copies the manifest somewhere.

For packages, the manifest (and any pre-/post-installation script referenced in it) is stored in `administrator/manifests/packages`.

The fact that the manifest is missing means that you somehow deleted it from `administrator/manifests/packages`.

The way you should deal with that is re–install the package (so Joomla writes back the missing manifest), the uninstall it.

What you've done has broken your site in subtle but important ways. If you come back to me with problems such as an update to our extension appears after you “uninstalled” it (you didn't; you only messed up its installation), why does it prevent you from updating Joomla , permissions issues etc I will tell you it's exactly because you did something you shouldn't have. Not my fault, not my problem, not worth wasting my time. I am responsible for my code, not for stupid things people do with their sites.

**Comment by Damnatus** [comment]
I have exactly done that first: 
I have let Joomla install the zip multiple times (6 times to be precise) with the error persisting.
Because I read on an Akeeba Support Ticket that the installer can be unreliable at times.
I never had that issue. That is why it crossed my mind that there could be an issue with the zip/component.

In fact, the manifest is still at the location as I just looked up the manifest location. 

<img width="902" alt="Screenshot 2021-09-24 at 08 13 29" src="https://user-images.githubusercontent.com/7227343/134627844-96e8dd4e-2d14-465b-8986-ab1429558cd0.png">

I have removed it manually because I've read here that you **do not provide end user support**.
I wanted to try to bring a potential issue to your attention as I'm using other Akeeba products since 2013 and had no issues with them. I wanted to be helpful. But you're condescending. Okay. Rough day already in the morning?
  
I will use Akeeba Backup to play back a backup from before installing the component.

**Comment by nikosdion** [comment]
> But you're condescending. Okay. Rough day already in the morning?

Not the least bit. Weather's finally cool, woke up before the alarm, had my coffee, one of my Joomla PRs is merged and I am having an overall pleasant, productive morning this issue notwithstanding.

I am not being condescending, I am being _FACTUAL_. I am sorry that your feelings are hurt from hearing the bitter truth. The thing is, Joomla doesn't care about your feelings. It only cares about data consistency and you've broken it. As a result several things will go wrong with your site. I'm honestly very tired of wasting time helping people who shoot their feet off and then blame me for their ill–advised actions, even more so when they come proudly telling me they shoot their feet off to begin with! It was funny the first 20 times it happened 15 years ago. Having to deal with that 100 times a year over the past 15 years it's annoying as hell. So when I tel you I won't help you I mean it; I'm done wasting my time with people breaking their sites and blaming me because they don't understand that my code has fuck all to do with what Joomla does on installation, update, re–installation and uninstallation of extensions. OK? Are we clear?

So let me tell you how you have broken your site.

When you try to upgrade to a new Joomla version family it will tell you that my software is incompatible with it and prevent you from upgrading. You will also see updates to my software you think to have uninstalled. Both are because the update site and package extension information is left behind.

If you delete the extensions table data you are left with orphan assets entries which will cause permissions issues. If you delete the assets entries you create holes in the tree structure of the assets table which will cause problems in the future, as we saw happening a lot with people upgrading their Joomla 1.6/1.7/2.5 sites to Joomla 3 after they had gone angry ape on their site's database.

So now let me tell you what I would have done in your shoes.

First, I'd have tried what I already said — install the package, make sure there are no installation errors, then try to uninstall it.

If Joomla keeps saying that it cannot find the manifest I'd go the manual uninstallation route. First, I'd look in the ZIP package to see which extensions are installed by it. The, I would go to Extensions, Manage and uninstall them one by one. As I said, you cannot uninstall FOF 4 and FEF 2. You will eventually be able to do that in a future update; but that's not something worth discussing here.

The next thing I'd do is troubleshoot why the hell Joomla thinks there is no package manifest. I understand how the Joomla installer works and I know that you can't install a package if the manifest is broken or missing. The very fact that you have the package installed says something is wrong with Joomla. This involves some messing around with the `#__extensions` table and I am not comfortable giving generic instructions out of fear that someone who doesn't understand what they are doing will actually attempt to follow them and cause a bigger problem. Basically, Joomla uses the information in the package name to figure out what the manifest XML file is named. If it messed it up on installation (os someone messed it up after the installation) Joomla won't replace it on reinstallation and you're stuck. Well, it _is_ a Joomla issue with no backwards compatible solution I can see anyone being able to implement.

So the final thing I'd advise someone to do is go to the Update Sites page and remove the update site to Engage.

Joomla will still complain that Engage is incompatible with a future version of Joomla but you can ignore that and upgrade Joomla. You still have a leftover `#__extensions` table entry but it's only the one for the package (not a component!) which causes no other hard beyond the annoying Joomla message on update to a new Joomla version family.
